#%RAML 1.0 DataType

type: object
properties: 
  id: string
  name?: string
  title?: string
  email?: string
  phone?: string
  address?: string
  postal?: string
  city?: string
  country?: string
  accountName?: string