#%RAML 1.0 NamedExample
value: 
  - id: "0032E00002SrMoIQAV"
    name: "Arthur Song"
    title: "Financial Controller"
    email: "asong@example.com"
    phone: "(772) 555-5429"
    address: "3418 Poplar Ave"
    postal: "38111"
    city: "Shelby"
    country: "USA"
    accountName: "Vand Enterprises, Inc."
  - id: "0032E00002SrMnwQAF"
    name: "Allison Yates"
    title: "Owner"
    email: "ayates@example.com"
    phone: "(239) 555-1562"
    address: "390 Harris Street"
    postal: "2007"
    city: "Sydney"
    country: "Australia"
    accountName: "Morpon Brothers"
  - id: "0032E00002SrMmuQAF"
    name: "Mark Metz"
    title: "Chief Executive Officer"
    email: "mmetz@example.com"
    phone: "(747) 555-0100"
    address: "1 Market St"
    postal: "94105"
    city: "San Francisco"
    country: "USA"
    accountName: "Advanced Communications"