#%RAML 1.0 NamedExample
value:
  id: "0032E00002SrMoIQAV"
  name: "Arthur Song"
  title: "Financial Controller"
  email: "asong@example.com"
  phone: "(772) 555-5429"
  address: "3418 Poplar Ave"
  postal: "38111"
  city: "Shelby"
  country: "USA"
  accountName: "Vand Enterprises, Inc."